apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: postgresql
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials

  storage:
    size: 5Gi

  monitoring:
    enablePodMonitor: false
