apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openzaak-postgres
  namespace: postgresql
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgis:17

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: openzaak
      owner: openzaak
      secret:
        name: openzaak-db-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;

  storage:
    size: 10Gi

  monitoring:
    enablePodMonitor: false
