apiVersion: batch/v1
kind: Job
metadata:
  name: objecten-create-postgis
  namespace: postgresql
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: ghcr.io/cloudnative-pg/postgis:17
          command:
            - /bin/sh
            - -c
            - |
              psql "host=objecten-postgres-rw dbname=objecten" -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: objecten-postgres-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: objecten-postgres-superuser
                  key: password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: openzaak-create-postgis
  namespace: postgresql
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: ghcr.io/cloudnative-pg/postgis:17
          command:
            - /bin/sh
            - -c
            - |
              psql "host=openzaak-postgres-rw dbname=openzaak" -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: openzaak-postgres-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: openzaak-postgres-superuser
                  key: password
