apiVersion: v1
kind: Secret
metadata:
  name: objecttypen-secrets
  namespace: objecttypen
type: Opaque
stringData:
  SECRET_KEY: "il0(c^etvh)@nq%v#$w4qm$z24dv%h(_a=9vf4u517!i_vro6p"   # genereer op https://djecrety.ir/
  DB_PASSWORD: "test123"
