apiVersion: v1
kind: Secret
metadata:
  name: objecttypen-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: objecttypen
  password: "VERVANG_MET_DB_WACHTWOORD"   # zelfde als DB_PASSWORD in objecttypen-secrets
