apiVersion: v1
kind: Secret
metadata:
  name: objecten-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: objecten
  password: "test123"   # zelfde als DB_PASSWORD in objecten-secrets
