apiVersion: v1
kind: Secret
metadata:
  name: objecten-secrets
  namespace: objecten
type: Opaque
stringData:
  SECRET_KEY: "VERVANG_MET_DJANGO_SECRET_KEY"   # genereer op https://djecrety.ir/
  DB_PASSWORD: "VERVANG_MET_DB_WACHTWOORD"
