apiVersion: v1
kind: Secret
metadata:
  name: openzaak-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: openzaak
  password: "VERVANG_MET_DB_WACHTWOORD"   # zelfde als DB_PASSWORD in openzaak-secrets
