apiVersion: v1
kind: Secret
metadata:
  name: opennotificaties-rabbitmq
  namespace: opennotificaties
type: Opaque
stringData:
  rabbitmq-password: "VERVANG_MET_RABBITMQ_WACHTWOORD"
  rabbitmq-erlang-cookie: "VERVANG_MET_ERLANG_COOKIE"   # willekeurige string, min. 32 tekens
