apiVersion: v1
kind: Secret
metadata:
  name: opennotificaties-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: opennotificaties
  password: "test123"   # zelfde als DB_PASSWORD in opennotificaties-secrets
