apiVersion: v1
kind: Secret
metadata:
  name: opennotificaties-rabbitmq
  namespace: opennotificaties
type: Opaque
stringData:
  rabbitmq-password: "test123"
  rabbitmq-erlang-cookie: "test123"   # willekeurige string, min. 32 tekens
