apiVersion: v1
kind: Secret
metadata:
  name: opennotificaties-secrets
  namespace: opennotificaties
type: Opaque
stringData:
  SECRET_KEY: "q7or#stb_s6bz=a=-7))_!u_-2-$wv84-bju74=8xa%4**-#pw"   # genereer op https://djecrety.ir/
  DB_PASSWORD: "test123"
