apiVersion: v1
kind: Secret
metadata:
  name: openzaak-secrets
  namespace: openzaak
type: Opaque
stringData:
  SECRET_KEY: "&w25utd3x&4oy4n2iez6hvzghvh-2zw3&e36$gynblp+(12t(#"   # genereer op https://djecrety.ir/
  DB_PASSWORD: "test123"
